# Fuse Core Theme for Jekyll - Settings
# https://github.com/tsjensen/fuse-core

markdown: kramdown
permalink: pretty
exclude: ['README.*']
sass:
    style: expanded


# CAUTION
# When modifying this file, take care to preserve the indentation. This is YAML ...

# Main Headline, name required, subtitle optional
name: zmk's home
#subtitle:
subtitle: cn-dev

# Title attribute of HTML Page, uses 'name' from above if empty
title: zmk's home
# Information for web crawlers / Google, all of them optional
# 'description' and 'keywords' simply set the corresponding meta tags,
# 'crawl' is the 'Robots' tag http://www.robotstxt.org/meta.html
robots:
    description: One line of text describing the content of the page in less than 140 characters.
    keywords: foo, bar, baz
    crawl: index,follow

# website address when deployed, also given as canonical link
url: https://cn.hd.lc/index.html/

# The 'baseurl' is prepended to all website-internal links.
# 'baseurl' will often be '', but for a project page on gh-pages, it needs to be the project name.
# If not empty, be careful to keep the leading slash, and don't add a slash at the end.
#baseurl: ''
baseurl: '/'

# Enable Google Analytics. Leave empty (just "ga:" with subitems commented out) to disable.
# In order to comply with EU cookie law, enable 'cookieconsent' to show a little popup asking users to acknowledge the GA cookies.
# Also, some places require you to anonymize the users' IPs, which can be enabled via 'anonymizeip' below. You normally want that.
# https://support.google.com/analytics/answer/2763052
#ga:
ga:
    account: 'UA-120960520-1'
    cookieconsent: true
    anonymizeip: true

# Plausible.io Analytics (alternative to Google Analytics that does not need cookies -> no cookie consent required)
# A config setting is required in plausible to enable tracking of the outbound links. Details described here:
# https://plausible.io/docs/outbound-link-click-tracking
# Leave empty (just "plausible:" with subitems commented out) to disable.
#plausible:
plausible:
    domain: 'cn.hd.lc/index.html'




# All the social media and other sites that we want to link to. The 'show' flag determines if the link is shown.
# The order of this list controls the order of the links on the page. Feel free to add.
links:

      name: GitHub
      show: true
      href: https://github.com/wszmk
      icon: fab fa-github
  - codepen:
      name: Blog
      show: true
      href: https://cnblogs.com/js-cn
      icon: fas fa-book-open
  - stackoverflow:

# Extra HTML which will be displayed below the links. Keep it short. Leave empty to disable.
#extra_html:
extra_html: >
    Any (multiline) text containing simple HTML,
    such as links or ... lorem ipsum.

#EOF
